#!/usr/bin/env bash
# Superset workspace setup (runs inside each isolated worktree).
#
# 1. Install dependencies (pnpm's shared store makes this fast per worktree).
# 2. Regenerate the gitignored CLAUDE.md: worktrees live outside the zabloo-hub/
#    directory tree, so neither the umbrella CLAUDE.md nor the one generated by
#    ai-docs/setup.sh exists here. We rebuild it with absolute-path imports,
#    derived from the main checkout's location (no hardcoded paths). If the
#    private ai-docs repo is not present (external contributors), this is a no-op.
set -euo pipefail

# Doble install: la 1ª trae deps, `pnpm build` genera dist/cli.js, la 2ª
# repara el symlink del bin `zabloo` (pnpm no lo crea si dist/ aún no existe).
pnpm install --prefer-offline
pnpm build
pnpm install --prefer-offline

AI_DOCS="$(cd "${SUPERSET_ROOT_PATH:-.}/.." 2>/dev/null && pwd)/ai-docs"
if [ -d "$AI_DOCS" ] && [ ! -e CLAUDE.md ]; then
  cat > CLAUDE.md <<EOF
<!--
  GENERADO por .superset/setup.sh para este worktree — NO editar a mano, NO commitear.
  Fuente de verdad: el repo privado ai-docs/.
-->
# ui — contexto (worktree de Superset)

@$AI_DOCS/CONTEXT.md

@$AI_DOCS/ui/CONTEXT.md
EOF
  echo "✓ CLAUDE.md generado (importa $AI_DOCS)"
fi
