#!/usr/bin/env python3
"""Regenerates `core/src/generated/default_font.cpp` from the shared TTF.

The font is embedded rather than read from disk because the core has to be able
to lay text out with no engine, no filesystem and no asset pipeline around it —
that is the frontier of ZAB-134, and it is what lets the golden corpus run
against a bare binary. The generated file is committed, so building the core
never needs Python at all; this script is only re-run when the font changes.

    python3 core/scripts/embed_font.py

Base64 in chunks, not a byte array: 410 KB of `0x00,` is a 2 MB source file that
every compiler re-parses, while base64 is 550 KB and decodes once at startup.
The chunks exist because MSVC refuses a string literal over 65535 bytes, and
adjacent literals are concatenated into one — so they have to stay separate
array elements.
"""

import hashlib
import os
from base64 import b64encode

# Under 65535 bytes (MSVC's limit) and a multiple of 4, so every chunk is whole
# base64 and the decoder never has to carry state across one.
CHUNK = 32768

here = os.path.dirname(os.path.abspath(__file__))
core = os.path.dirname(here)
repo = os.path.dirname(core)

FONT = os.path.join(repo, "assets", "fonts", "LiberationSans-Regular.ttf")
OUT = os.path.join(core, "src", "generated", "default_font.cpp")


def main():
    with open(FONT, "rb") as handle:
        payload = handle.read()
    digest = hashlib.sha256(payload).hexdigest()
    base64 = b64encode(payload).decode("ascii")
    chunks = [base64[i : i + CHUNK] for i in range(0, len(base64), CHUNK)]

    lines = [
        "// GENERATED by core/scripts/embed_font.py — do not edit by hand.",
        "// source: assets/fonts/LiberationSans-Regular.ttf"
        " (%d bytes, sha256 %s)" % (len(payload), digest),
        "",
        '#include "default_font.h"',
        "",
        "#include <cstdint>",
        "",
        "namespace zabloo {",
        "namespace {",
        "",
        "/**",
        " * Liberation Sans Regular (SIL OFL 1.1 — see assets/fonts/), the shared TTF",
        " * every zabloo target rasterizes. Metric-compatible with Arial, and the same",
        " * bytes `@zabloo/renderer-web` embeds in `src/generated/font.ts`: same font and",
        " * same rasterizer is what makes a line break in the same place on both.",
        " *",
        " * Split into pieces because MSVC refuses a string literal over 65535 bytes.",
        " */",
        "const char *const CHUNKS[] = {",
    ]
    for chunk in chunks:
        lines.append('    "%s",' % chunk)
    lines += [
        "};",
        "",
        "/** Base64 digit → its 6 bits, or 0xff for anything that is not one. */",
        "uint8_t sextet(char digit) {",
        "  if (digit >= 'A' && digit <= 'Z') return static_cast<uint8_t>(digit - 'A');",
        "  if (digit >= 'a' && digit <= 'z') return static_cast<uint8_t>(digit - 'a' + 26);",
        "  if (digit >= '0' && digit <= '9') return static_cast<uint8_t>(digit - '0' + 52);",
        "  if (digit == '+') return 62;",
        "  if (digit == '/') return 63;",
        "  return 0xff;",
        "}",
        "",
        "std::vector<uint8_t> decode() {",
        "  std::vector<uint8_t> out;",
        "  out.reserve(%d);" % len(payload),
        "  uint32_t bits = 0;",
        "  int filled = 0;",
        "  for (const char *const chunk : CHUNKS) {",
        "    for (const char *digit = chunk; *digit != '\\0'; digit++) {",
        "      const uint8_t value = sextet(*digit);",
        "      if (value == 0xff) continue;  // padding",
        "      bits = (bits << 6) | value;",
        "      filled += 6;",
        "      if (filled >= 8) {",
        "        filled -= 8;",
        "        out.push_back(static_cast<uint8_t>((bits >> filled) & 0xff));",
        "      }",
        "    }",
        "  }",
        "  return out;",
        "}",
        "",
        "}  // namespace",
        "",
        "const std::vector<uint8_t> &default_font_bytes() {",
        "  // Decoded once, on first use: ~410 KB, and a UI that never draws a glyph",
        "  // (there is no such UI, but the core does not know that) never pays it.",
        "  static const std::vector<uint8_t> bytes = decode();",
        "  return bytes;",
        "}",
        "",
        "}  // namespace zabloo",
        "",
    ]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(
        "wrote %s (%d chunks, sha256 %s…)"
        % (os.path.relpath(OUT, repo), len(chunks), digest[:12])
    )


if __name__ == "__main__":
    main()
